server:
  port: 9021
spring:
  config:
    import: classpath:bootstrap.yaml
  application:
    name: consumer-service

### feign 配置
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        # 打印日志级别
        logger-level: headers
        # 配置 feign 拦截器
        request-interceptors:
          - com.guorong.consumer.feign.CustomRequestInterceptor
### 日志配置
logging:
  level:
    com.guorong.consumer.feign: debug

### dubbo配置
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
    group: dubbo-service

### 自定义配置
nacos:
  server-address: 192.168.56.104
  port: 8848
  username: nacos
  password: nacos
rest:
  server-url: http://provider-service
