### 测试返回枚举  ["SMALL","MIDDLE","BIG"]
GET http://localhost:8080/enum/listSizeTypeEnum


### 测试枚举 [{"code": "spring","name": "春天"},{"code": "summer","name": "夏天"},{"code": "autumn","name": "秋天"},{"code": "winter","name": "冬天"}]
GET http://localhost:8080/enum/listSeasonEnum


### 测试 ["黑种人","白种人","黄种人"]
GET http://localhost:8080/enum/listPersonTypeEnum




