server:
  port: 8080
spring:
  datasource:
    # 主数据库
    master:
      name: master
      url: jdbc:h2:mem:${spring.datasource.master.name}
      username: root
      password: 123456
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
    # 从数据库
    slave:
      name: slave
      url: jdbc:h2:mem:${spring.datasource.slave.name}
      username: root
      password: 123456
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: true
      path: /h2-console
