server:
  port: 8080 # 服务端口


spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_learning?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: springboot_learning
    password: springboot_learning
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:
  application:
    # 应用程序名称
    name: springboot-jpa



# 日志
logging:
  level:
    root: debug
    com.guorong.jpa.repository: debug
  path: /logs/
  file: spring-boot-jpa.log
